### ISSUE TITLE
Storage badusb

### ISSUE THREAD

**Issue by FalsePhilosopher** [whitenois3/sophia#1]
Reading through your duckies I noticed Attackmod hid storage, that's a ducky v3 thing and the fz barely supports ducky v1 scripting. You can read through the FW and see what all is supported here
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/bad_usb/bad_usb_script.c

**Comment by refcell** [comment]
Oh amazing, thanks for linking! Yes that was accidentally left in from my initial testing!
